# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Erica Fremming
email: ericafremming@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This site is serving as a learning space for the creation
  of static websites and hopefully as an archive of learning, ideas, projects and works in progress 
  for the future.
#baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://ericaerinf.com" # the base hostname & protocol for your site
twitter_username:
github_username: ericaerinf
permalink: /:title

# Build settings
markdown: kramdown
port: 4000